version: '3.8'

services:
  shorts-ai-agent:
    build: .
    container_name: shorts-ai-agent
    ports:
      - "5000:5000"
    volumes:
      # Mount videos directory to persist generated videos
      - ./videos:/app/videos
      # Mount environment file (create this file with your API keys)
      - ./.env:/app/.env:ro
      # Mount styles directory for style images
      - ./styles:/app/styles
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
